#!/usr/bin/env node
'use strict';
/**
 * build_founder_photos.js — bakes the two founder headshots into app/founder_photos.js
 * as opaque, print-sized data URIs for the client report v3 Welcome page.
 *
 * WHY THE SOURCES ARE NOT USED DIRECTLY
 * -------------------------------------
 * 1. ALPHA. The supplied Cai headshot is a ROUND crop: measured, 23.0% of its pixels are
 *    fully transparent (the corners outside the circle) and 0.6% are semi-transparent (the
 *    antialiased circle edge). Chromium emits an /SMask soft mask for any alpha imagery, and
 *    design spec v3.0 section 3.2 forbids soft masks document-wide — it is the mechanism
 *    that rendered the cover PINK in one PDF viewer. scripts/verify_transparency.js fails
 *    the build on a single soft mask, so embedding the round PNG as-is would break the gate.
 *
 *    The fix is to flatten onto opaque white and drop the alpha channel entirely, then do
 *    the circular crop in CSS (border-radius + overflow:hidden), which is how .v3-wl-av
 *    already works. Visually identical, zero soft masks. Flattening is lossless here because
 *    the page behind the photo is white anyway.
 *
 * 2. SIZE. The supplied Mo headshot is 2623x2623 and 18.31 MB. The photo renders in a 110px
 *    circle, so the source is ~12x more resolution than the layout can use and would bloat
 *    every generated PDF.
 *
 * 3. REPRODUCIBILITY. Baking by hand would leave an unexplained blob in the tree. This
 *    script records the exact transform and the source digests, so the module can be
 *    regenerated and verified against the originals.
 *
 * The sources live in docs/ and are deliberately NOT committed — 18.31 MB of JPEG does not
 * belong in the repo. Their sha256 digests are recorded in the generated file so the inputs
 * remain identifiable. Re-run this only when the photography changes.
 *
 *   node scripts/build_founder_photos.js
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..');
const sharp = require(path.join(ROOT, 'app/node_modules/sharp'));

// Rendered at 110px (brief v1.7 locked 84px; raised on Cai's direction 12 Aug). Embedded at
// 2x so the raster still holds up when the PDF is printed or zoomed; 3x was measured at
// ~2.3x the bytes for no visible gain.
//
// SOURCE CEILING: the supplied Cai headshot is 300x299, so a true 2x embed caps the rendered
// circle at 150px. 110px needs 220px and is comfortably inside that. Anything above 150px
// requires a new source file rather than an upscale — sharp would happily enlarge and the
// result would be soft on print with nothing failing. Mo's 2623x2623 source is unconstrained.
const RENDER_PX = 110;
const SCALE = 2;
const EDGE = RENDER_PX * SCALE;

const SOURCES = [
  { key: 'cai', name: 'Cai Delumpa', file: 'docs/hive_cai_headshot-round_kit_091125.png' },
  { key: 'mo', name: 'Monique Breault', file: 'docs/mo_headshot_square_07162-4.jpeg' },
];

(async () => {
  const out = [];
  for (const s of SOURCES) {
    const abs = path.join(ROOT, s.file);
    if (!fs.existsSync(abs)) {
      console.error(`MISSING SOURCE: ${s.file}`);
      process.exit(1);
    }
    const raw = fs.readFileSync(abs);
    const meta = await sharp(raw).metadata();

    const buf = await sharp(raw)
      // Square first: the Cai source is 300x299, so a straight resize would distort it.
      .resize(EDGE, EDGE, { fit: 'cover', position: 'centre' })
      // Opaque white behind, then drop the channel. Both are needed: flatten alone leaves a
      // 4-channel image whose alpha is all-255, and Chromium still emits a mask for it.
      .flatten({ background: '#FFFFFF' })
      .removeAlpha()
      // Strip ICC/EXIF: colour management metadata is not needed for a 110px circle and only
      // adds bytes to every PDF.
      .jpeg({ quality: 86, chromaSubsampling: '4:4:4', mozjpeg: true })
      .toBuffer();

    const after = await sharp(buf).metadata();
    if (after.hasAlpha) { console.error(`${s.key}: still has alpha after normalization`); process.exit(1); }

    out.push({
      ...s,
      sha: crypto.createHash('sha256').update(raw).digest('hex'),
      srcDesc: `${meta.format} ${meta.width}x${meta.height} ch=${meta.channels} alpha=${!!meta.hasAlpha} ${(raw.length / 1024 / 1024).toFixed(2)} MB`,
      b64: buf.toString('base64'),
      bytes: buf.length,
    });
    console.log(`  ${s.key.padEnd(4)} ${meta.width}x${meta.height} ${meta.format}${meta.hasAlpha ? ' (alpha)' : ''} ` +
      `-> ${EDGE}x${EDGE} jpeg opaque, ${(buf.length / 1024).toFixed(1)} KB`);
  }

  const body = `'use strict';
/**
 * founder_photos.js — GENERATED by scripts/build_founder_photos.js. Do not hand-edit.
 *
 * The two founder headshots for the client report v3 Welcome page, as opaque JPEG data URIs
 * at ${EDGE}px (${RENDER_PX}px rendered, ${SCALE}x for print).
 *
 * Both are flattened onto white with the alpha channel REMOVED. The Cai source is a round
 * crop whose corners are transparent; embedding it with alpha makes Chromium emit an /SMask
 * soft mask, which design spec v3.0 section 3.2 forbids document-wide and
 * scripts/verify_transparency.js fails the build on. The circular crop is done in CSS
 * instead (.v3-wl-av: border-radius 50% + overflow hidden).
 *
 * Sources (not committed — see the generator's header):
${out.map(o => ` *   ${o.key}: ${o.file}\n *       ${o.srcDesc}\n *       sha256 ${o.sha}`).join('\n')}
 */

${out.map(o => `// ${o.name} — ${(o.bytes / 1024).toFixed(1)} KB\nconst ${o.key.toUpperCase()}_PHOTO_DATA_URI = 'data:image/jpeg;base64,${o.b64}';`).join('\n\n')}

module.exports = { ${out.map(o => `${o.key.toUpperCase()}_PHOTO_DATA_URI`).join(', ')} };
`;

  const dest = path.join(ROOT, 'app/founder_photos.js');
  fs.writeFileSync(dest, body);
  console.log(`\nwrote app/founder_photos.js (${(fs.statSync(dest).size / 1024).toFixed(1)} KB)`);
})().catch(e => { console.error(e.stack || e.message); process.exit(1); });
